#############################################################################
# Makefile for building: dashboard
# Generated by qmake (3.1) (Qt 6.8.0)
# Project:  dashboard.pro
# Template: subdirs
# Command: D:\Qt\6.8.0\msvc2022_64\bin\qmake.exe -o Makefile dashboard.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\Qt\6.8.0\msvc2022_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\6.8.0\msvc2022_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\6.8.0\msvc2022_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-common \
		sub-BIWidgets \
		sub-plugins \
		sub-BIDesigner \
		sub-test-CommonTest


sub-common-qmake_all:  FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	cd common\ && $(QMAKE) -o Makefile E:\project\dashboard\common\common.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && $(MAKE) -f Makefile qmake_all
sub-common: $(MAKEFILE) FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\common\common.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile
sub-common-make_first: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\common\common.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile 
sub-common-all: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\common\common.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile all
sub-common-clean: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\common\common.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile clean
sub-common-distclean: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\common\common.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-common-install_subtargets: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\common\common.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile install
sub-common-uninstall_subtargets: FORCE
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\common\common.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-BIWidgets-qmake_all:  FORCE
	@if not exist BIWidgets\ mkdir BIWidgets\ & if not exist BIWidgets\ exit 1
	cd BIWidgets\ && $(QMAKE) -o Makefile E:\project\dashboard\BIWidgets\BIWidgets.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIWidgets\ && $(MAKE) -f Makefile qmake_all
sub-BIWidgets: $(MAKEFILE) FORCE
	@if not exist BIWidgets\ mkdir BIWidgets\ & if not exist BIWidgets\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIWidgets\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIWidgets\BIWidgets.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile
sub-BIWidgets-make_first: FORCE
	@if not exist BIWidgets\ mkdir BIWidgets\ & if not exist BIWidgets\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIWidgets\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIWidgets\BIWidgets.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile 
sub-BIWidgets-all: FORCE
	@if not exist BIWidgets\ mkdir BIWidgets\ & if not exist BIWidgets\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIWidgets\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIWidgets\BIWidgets.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile all
sub-BIWidgets-clean: FORCE
	@if not exist BIWidgets\ mkdir BIWidgets\ & if not exist BIWidgets\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIWidgets\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIWidgets\BIWidgets.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile clean
sub-BIWidgets-distclean: FORCE
	@if not exist BIWidgets\ mkdir BIWidgets\ & if not exist BIWidgets\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIWidgets\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIWidgets\BIWidgets.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-BIWidgets-install_subtargets: FORCE
	@if not exist BIWidgets\ mkdir BIWidgets\ & if not exist BIWidgets\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIWidgets\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIWidgets\BIWidgets.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile install
sub-BIWidgets-uninstall_subtargets: FORCE
	@if not exist BIWidgets\ mkdir BIWidgets\ & if not exist BIWidgets\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIWidgets\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIWidgets\BIWidgets.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-plugins-qmake_all:  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	cd plugins\ && $(QMAKE) -o Makefile E:\project\dashboard\plugins\plugins.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && $(MAKE) -f Makefile qmake_all
sub-plugins: $(MAKEFILE) FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\plugins\plugins.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile
sub-plugins-make_first: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\plugins\plugins.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile 
sub-plugins-all: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\plugins\plugins.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile all
sub-plugins-clean: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\plugins\plugins.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile clean
sub-plugins-distclean: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\plugins\plugins.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-plugins-install_subtargets: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\plugins\plugins.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile install
sub-plugins-uninstall_subtargets: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\plugins\plugins.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-BIDesigner-qmake_all:  FORCE
	@if not exist BIDesigner\ mkdir BIDesigner\ & if not exist BIDesigner\ exit 1
	cd BIDesigner\ && $(QMAKE) -o Makefile E:\project\dashboard\BIDesigner\BIDesigner.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIDesigner\ && $(MAKE) -f Makefile qmake_all
sub-BIDesigner: $(MAKEFILE) FORCE
	@if not exist BIDesigner\ mkdir BIDesigner\ & if not exist BIDesigner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIDesigner\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIDesigner\BIDesigner.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile
sub-BIDesigner-make_first: FORCE
	@if not exist BIDesigner\ mkdir BIDesigner\ & if not exist BIDesigner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIDesigner\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIDesigner\BIDesigner.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile 
sub-BIDesigner-all: FORCE
	@if not exist BIDesigner\ mkdir BIDesigner\ & if not exist BIDesigner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIDesigner\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIDesigner\BIDesigner.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile all
sub-BIDesigner-clean: FORCE
	@if not exist BIDesigner\ mkdir BIDesigner\ & if not exist BIDesigner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIDesigner\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIDesigner\BIDesigner.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile clean
sub-BIDesigner-distclean: FORCE
	@if not exist BIDesigner\ mkdir BIDesigner\ & if not exist BIDesigner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIDesigner\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIDesigner\BIDesigner.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-BIDesigner-install_subtargets: FORCE
	@if not exist BIDesigner\ mkdir BIDesigner\ & if not exist BIDesigner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIDesigner\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIDesigner\BIDesigner.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile install
sub-BIDesigner-uninstall_subtargets: FORCE
	@if not exist BIDesigner\ mkdir BIDesigner\ & if not exist BIDesigner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIDesigner\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIDesigner\BIDesigner.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-test-CommonTest-qmake_all:  FORCE
	@if not exist test\CommonTest\ mkdir test\CommonTest\ & if not exist test\CommonTest\ exit 1
	cd test\CommonTest\ && $(QMAKE) -o Makefile E:\project\dashboard\test\CommonTest\CommonTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd test\CommonTest\ && $(MAKE) -f Makefile qmake_all
sub-test-CommonTest: $(MAKEFILE) FORCE
	@if not exist test\CommonTest\ mkdir test\CommonTest\ & if not exist test\CommonTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd test\CommonTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\test\CommonTest\CommonTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile
sub-test-CommonTest-make_first: FORCE
	@if not exist test\CommonTest\ mkdir test\CommonTest\ & if not exist test\CommonTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd test\CommonTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\test\CommonTest\CommonTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile 
sub-test-CommonTest-all: FORCE
	@if not exist test\CommonTest\ mkdir test\CommonTest\ & if not exist test\CommonTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd test\CommonTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\test\CommonTest\CommonTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile all
sub-test-CommonTest-clean: FORCE
	@if not exist test\CommonTest\ mkdir test\CommonTest\ & if not exist test\CommonTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd test\CommonTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\test\CommonTest\CommonTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile clean
sub-test-CommonTest-distclean: FORCE
	@if not exist test\CommonTest\ mkdir test\CommonTest\ & if not exist test\CommonTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd test\CommonTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\test\CommonTest\CommonTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-test-CommonTest-install_subtargets: FORCE
	@if not exist test\CommonTest\ mkdir test\CommonTest\ & if not exist test\CommonTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd test\CommonTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\test\CommonTest\CommonTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile install
sub-test-CommonTest-uninstall_subtargets: FORCE
	@if not exist test\CommonTest\ mkdir test\CommonTest\ & if not exist test\CommonTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd test\CommonTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\test\CommonTest\CommonTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: dashboard.pro D:\Qt\6.8.0\msvc2022_64\mkspecs\win32-msvc\qmake.conf D:\Qt\6.8.0\msvc2022_64\mkspecs\features\spec_pre.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\common\windows-desktop.conf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\common\windows-vulkan.conf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\common\msvc-desktop.conf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\qconfig.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_freetype.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_libjpeg.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_libpng.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_openxr_loader.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3danimation.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dcore.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dextras.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dinput.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dlogic.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquick.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3drender.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3drender_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_activeqt.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_activeqt_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_axbase_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_axcontainer.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_axserver.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_axserver_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_bluetooth.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_bodymovin_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_charts.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_charts_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_chartsqml.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_chartsqml_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_concurrent.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_core.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_core5compat.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_core5compat_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_core_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_datavisualization.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_datavisualizationqml.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_datavisualizationqml_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_dbus.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_dbus_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_designer.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_designer_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_entrypoint_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_example_icons_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_examples_asset_downloader_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_freetype_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_graphs.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_graphs_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_graphswidgets.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_graphswidgets_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_grpc.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_grpc_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_grpcquick.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_grpcquick_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_gui.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_gui_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_harfbuzz_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_help.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_help_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_httpserver.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_httpserver_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_jpeg_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_jsonrpc_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsanimation.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsanimation_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsplatform.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsplatform_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssettings.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssettings_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_languageserver_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_linguist.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_location.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_location_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_multimedia.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_multimediaquick_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_network.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_network_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_networkauth.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_nfc.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_nfc_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_opengl.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_opengl_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_openxr_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_png_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_positioning.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_positioning_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_positioningquick.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_printsupport.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobuf.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobuf_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufqtcoretypes.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufqtcoretypes_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufqtguitypes.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufqtguitypes_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufquick.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufquick_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufwellknowntypes.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufwellknowntypes_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qdoccatch_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchconversions_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchgenerators_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qml.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qml_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcore.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcore_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmldom_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlls_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltest.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltoolingsettings_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3d.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3d_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetutils.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3deffects.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3deffects_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpers.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3diblbaker.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticles.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysics.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysics_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysicshelpers.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysicshelpers_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dspatialaudio_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dutils.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dxr.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dxr_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickeffects_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktimeline.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktimeline_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktimelineblendtrees.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktimelineblendtrees_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimagegenerator_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_repparser.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_repparser_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_scxml.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_scxml_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_scxmlqml.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_scxmlqml_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sensors.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sensors_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sensorsquick.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sensorsquick_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_serialbus.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_serialport.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_serialport_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_shadertools.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_shadertools_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_spatialaudio.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_spatialaudio_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sql.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sql_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_statemachine.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_statemachine_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_statemachineqml.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_statemachineqml_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svg.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svg_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_testlib.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_testlib_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_texttospeech.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_tools_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_uiplugin.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_uitools.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_uitools_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboardsettings.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboardsettings_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webchannel.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webchannelquick.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webchannelquick_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_websockets.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_websockets_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webview.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webview_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webviewquick.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webviewquick_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_widgets.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_widgets_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_xml.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_xml_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_zlib_private.pri \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\qt_functions.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\qt_config.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\win32-msvc\qmake.conf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\exclusive_builds.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\common\msvc-version.conf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\toolchain.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\default_pre.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\win32\default_pre.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\resolve_config.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\exclusive_builds_post.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\default_post.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\precompile_header.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\warn_on.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\qmake_use.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\file_copies.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\win32\windows.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\testcase_targets.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\exceptions.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\yacc.prf \
		D:\Qt\6.8.0\msvc2022_64\mkspecs\features\lex.prf \
		dashboard.pro
	$(QMAKE) -o Makefile dashboard.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug"
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\spec_pre.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\common\windows-desktop.conf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\common\windows-vulkan.conf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\common\msvc-desktop.conf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\qconfig.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_freetype.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_libjpeg.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_libpng.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_openxr_loader.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3danimation.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3danimation_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dcore.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dcore_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dextras.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dextras_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dinput.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dinput_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dlogic.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquick.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquick_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickextras.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickinput.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickrender.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3drender.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_3drender_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_activeqt.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_activeqt_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_axbase_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_axcontainer.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_axserver.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_axserver_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_bluetooth.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_bodymovin_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_charts.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_charts_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_chartsqml.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_chartsqml_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_concurrent.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_concurrent_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_core.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_core5compat.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_core5compat_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_core_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_datavisualization.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_datavisualizationqml.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_datavisualizationqml_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_dbus.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_dbus_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_designer.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_designer_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_entrypoint_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_example_icons_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_examples_asset_downloader_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_fb_support_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_freetype_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_graphs.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_graphs_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_graphswidgets.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_graphswidgets_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_grpc.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_grpc_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_grpcquick.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_grpcquick_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_gui.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_gui_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_harfbuzz_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_help.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_help_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_httpserver.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_httpserver_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_jpeg_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_jsonrpc_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsanimation.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsanimation_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsplatform.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsplatform_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssettings.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssettings_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_languageserver_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_linguist.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_location.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_location_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_multimedia.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_multimedia_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_multimediaquick_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_network.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_network_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_networkauth.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_networkauth_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_nfc.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_nfc_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_opengl.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_opengl_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_openxr_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_png_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_positioning.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_positioning_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_positioningquick.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_printsupport.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_printsupport_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobuf.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobuf_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufqtcoretypes.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufqtcoretypes_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufqtguitypes.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufqtguitypes_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufquick.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufquick_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufwellknowntypes.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_protobufwellknowntypes_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qdoccatch_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchconversions_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchgenerators_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qml.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qml_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcore.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcore_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmldom_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlls_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltest.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltest_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltoolingsettings_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3d.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3d_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetimport.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetutils.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3deffects.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3deffects_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpers.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3diblbaker.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticles.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysics.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysics_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysicshelpers.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysicshelpers_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3druntimerender.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dspatialaudio_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dutils.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dutils_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dxr.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick3dxr_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickeffects_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktimeline.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktimeline_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktimelineblendtrees.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktimelineblendtrees_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimagegenerator_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_remoteobjects.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_repparser.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_repparser_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_scxml.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_scxml_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_scxmlqml.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_scxmlqml_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sensors.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sensors_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sensorsquick.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sensorsquick_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_serialbus.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_serialbus_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_serialport.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_serialport_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_shadertools.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_shadertools_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_spatialaudio.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_spatialaudio_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sql.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sql_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_statemachine.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_statemachine_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_statemachineqml.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_statemachineqml_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svg.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svg_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_testlib.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_testlib_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_texttospeech.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_tools_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_uiplugin.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_uitools.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_uitools_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboard.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboardsettings.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboardsettings_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webchannel.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webchannel_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webchannelquick.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webchannelquick_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_websockets.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_websockets_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webview.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webview_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webviewquick.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_webviewquick_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_widgets.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_widgets_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_xml.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_xml_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_zlib_private.pri:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\qt_functions.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\qt_config.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\win32-msvc\qmake.conf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\spec_post.prf:
.qmake.stash:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\exclusive_builds.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\common\msvc-version.conf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\toolchain.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\default_pre.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\win32\default_pre.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\resolve_config.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\exclusive_builds_post.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\default_post.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\precompile_header.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\warn_on.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\qmake_use.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\file_copies.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\win32\windows.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\testcase_targets.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\exceptions.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\yacc.prf:
D:\Qt\6.8.0\msvc2022_64\mkspecs\features\lex.prf:
dashboard.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile dashboard.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug"

qmake_all: sub-common-qmake_all sub-BIWidgets-qmake_all sub-plugins-qmake_all sub-BIDesigner-qmake_all sub-test-CommonTest-qmake_all FORCE

make_first: sub-common-make_first sub-BIWidgets-make_first sub-plugins-make_first sub-BIDesigner-make_first sub-test-CommonTest-make_first  FORCE
all: sub-common-all sub-BIWidgets-all sub-plugins-all sub-BIDesigner-all sub-test-CommonTest-all  FORCE
clean: sub-common-clean sub-BIWidgets-clean sub-plugins-clean sub-BIDesigner-clean sub-test-CommonTest-clean  FORCE
distclean: sub-common-distclean sub-BIWidgets-distclean sub-plugins-distclean sub-BIDesigner-distclean sub-test-CommonTest-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-common-install_subtargets sub-BIWidgets-install_subtargets sub-plugins-install_subtargets sub-BIDesigner-install_subtargets sub-test-CommonTest-install_subtargets FORCE
uninstall_subtargets: sub-common-uninstall_subtargets sub-BIWidgets-uninstall_subtargets sub-plugins-uninstall_subtargets sub-BIDesigner-uninstall_subtargets sub-test-CommonTest-uninstall_subtargets FORCE

sub-common-debug:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\common\common.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile debug
sub-BIWidgets-debug:
	@if not exist BIWidgets\ mkdir BIWidgets\ & if not exist BIWidgets\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIWidgets\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIWidgets\BIWidgets.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile debug
sub-plugins-debug:
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\plugins\plugins.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile debug
sub-BIDesigner-debug:
	@if not exist BIDesigner\ mkdir BIDesigner\ & if not exist BIDesigner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIDesigner\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIDesigner\BIDesigner.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile debug
sub-test-CommonTest-debug:
	@if not exist test\CommonTest\ mkdir test\CommonTest\ & if not exist test\CommonTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd test\CommonTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\test\CommonTest\CommonTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-common-debug sub-BIWidgets-debug sub-plugins-debug sub-BIDesigner-debug sub-test-CommonTest-debug

sub-common-release:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\common\common.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile release
sub-BIWidgets-release:
	@if not exist BIWidgets\ mkdir BIWidgets\ & if not exist BIWidgets\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIWidgets\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIWidgets\BIWidgets.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile release
sub-plugins-release:
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\plugins\plugins.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile release
sub-BIDesigner-release:
	@if not exist BIDesigner\ mkdir BIDesigner\ & if not exist BIDesigner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIDesigner\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIDesigner\BIDesigner.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile release
sub-test-CommonTest-release:
	@if not exist test\CommonTest\ mkdir test\CommonTest\ & if not exist test\CommonTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd test\CommonTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\test\CommonTest\CommonTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-common-release sub-BIWidgets-release sub-plugins-release sub-BIDesigner-release sub-test-CommonTest-release

sub-common-check:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\common\common.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile check
sub-BIWidgets-check:
	@if not exist BIWidgets\ mkdir BIWidgets\ & if not exist BIWidgets\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIWidgets\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIWidgets\BIWidgets.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile check
sub-plugins-check:
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\plugins\plugins.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile check
sub-BIDesigner-check:
	@if not exist BIDesigner\ mkdir BIDesigner\ & if not exist BIDesigner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIDesigner\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIDesigner\BIDesigner.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile check
sub-test-CommonTest-check:
	@if not exist test\CommonTest\ mkdir test\CommonTest\ & if not exist test\CommonTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd test\CommonTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\test\CommonTest\CommonTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-common-check sub-BIWidgets-check sub-plugins-check sub-BIDesigner-check sub-test-CommonTest-check

sub-common-benchmark:
	@if not exist common\ mkdir common\ & if not exist common\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd common\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\common\common.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-BIWidgets-benchmark:
	@if not exist BIWidgets\ mkdir BIWidgets\ & if not exist BIWidgets\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIWidgets\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIWidgets\BIWidgets.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-plugins-benchmark:
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\plugins\plugins.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-BIDesigner-benchmark:
	@if not exist BIDesigner\ mkdir BIDesigner\ & if not exist BIDesigner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd BIDesigner\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\BIDesigner\BIDesigner.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-test-CommonTest-benchmark:
	@if not exist test\CommonTest\ mkdir test\CommonTest\ & if not exist test\CommonTest\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd test\CommonTest\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\project\dashboard\test\CommonTest\CommonTest.pro -spec win32-msvc "CONFIG+=debug" "CONFIG-=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-common-benchmark sub-BIWidgets-benchmark sub-plugins-benchmark sub-BIDesigner-benchmark sub-test-CommonTest-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

