/*

 Copyright 2021 Google LLC
 This code is released under the MIT license.
 SPDX-License-Identifier: MIT
*/
function gvjs_I_(a){gvjs_Qn.call(this,a);this.zC=null;this.Sd=new gvjs_wi(this,this.container);this.Tra=gvjs_bma.push(this)-1;this.er=new gvjs_LT}gvjs_o(gvjs_I_,gvjs_Qn);gvjs_=gvjs_I_.prototype;gvjs_.setSelection=function(a){this.Of.setSelection(a)};gvjs_.getSelection=function(){return this.Of.getSelection()};
gvjs_.Rd=function(a,b,c){a=c||{};this.er.cancel();this.Of=new gvjs_$n;this.Sd.removeAll();if(this.Z=b)if(this.m=a,this.m.dataMode=a.dataMode||gvjs_yd,this.m.region=a.region||gvjs_CT,this.m.resolution=a.resolution||"",this.m.width=a.width||"556px",this.m.height=a.height||"347px",this.m.colors=a.colors||[14745556,10874723,5286400,2519316],this.m.showLegend=null==a.showLegend?!0:!!a.showLegend,this.m.showZoomOut=!!a.showZoomOut,this.m.zoomOutLabel=a.zoomOutLabel||"Zoom Out",gvjs_Yy(this.m.width)&&(this.m.width+=
gvjs_T),gvjs_Yy(this.m.height)&&(this.m.height+=gvjs_T),this.m.dataMode=this.m.dataMode.toUpperCase(),c=gvjs_J_[this.m.dataMode],null==c)this.Sd.Sc("Unsupported dataMode: "+this.m.dataMode);else{this.m.dataMode=c;this.m.useSvg=!!a.useSvg;try{var d=b.$();if(0==d)throw Error(gvjs_nT);if(4<d)throw Error("At most four data columns can be used.");a=[];a.push(b.W(0));if(1==d){if(a[0]!=gvjs_l)throw Error("Single column must be text.");}else{a.push(b.W(1));if(a[0]!=gvjs_g&&a[0]!=gvjs_l)throw Error("First column must be text or numbers.");
if(a[1]!=gvjs_g&&a[1]!=gvjs_l)throw Error("Second column must be text or numbers.");if(3<=d)if(a.push(b.W(2)),a[0]==gvjs_g&&a[1]==gvjs_g){if(a[2]!=gvjs_g)throw Error("Third column must be a numeric value.");}else if(a[2]!=gvjs_l)throw Error("Third column must be text.");if(4==d&&(a.push(b.W(3)),a[3]!=gvjs_l))throw Error("Forth column must be text.");}}catch(e){this.Sd.Sc(gvjs_pT);return}this.Z.W(0)==gvjs_l?(this.XP=!1,this.Nr=1,this.iF=2):(this.XP=!0,this.Nr=2,this.iF=3);b=this.Z.$()-1;b<this.Nr&&
(this.Nr=-1);b<this.iF&&(this.iF=-1);this.m.dataMode!=gvjs_J_.MARKERS&&this.XP?this.Sd.Sc("DataMode must be set to Markers when using lat/long addresses."):(this.Gi=Math.min(this.Z.ca(),400),this.Z.ca()>this.Gi&&this.Sd.Sc("Some of the data rows were truncated."),this.m.dataMode==gvjs_J_.MARKERS?this.XP?this.qX():this.pX():gvjs_He(gvjs_cma,this.m.region)?this.oX():this.rX())}else this.Sd.Sc(gvjs_as)};
gvjs_.oX=function(){for(var a=[],b=this.Z,c=0;c<this.Gi;c++){var d={},e=gvjs_gg(b.getValue(c,0));d.lat=null;d.lng=null;d.name=e;d.code=e.toUpperCase();a.push(d)}this.Ct=a;gvjs_pl(this.rE,0,this)};gvjs_.qX=function(){for(var a=[],b=this.Z,c=0;c<this.Gi;c++){var d={},e=b.getValue(c,0),f=b.getValue(c,1);null==e||null==f?a.push(null):(d.lat=gvjs_gg(e),d.lng=gvjs_gg(f),d.name=d.lat+gvjs_ha+d.lng,d.code=null,a.push(d))}this.Ct=a;gvjs_pl(this.rE,0,this)};
gvjs_.pX=function(){var a=[],b=this.Z,c="";2==this.m.region.length&&(c=this.m.region,c=c.toUpperCase(),c=c.replace(/GB/,"UK"),c=c.replace(/RU/,"SU"),c=c.replace(/TP/,"TL"));for(var d=0;d<this.Gi;d++){var e=gvjs_gg(b.getValue(d,0));gvjs_jf(c)||(e+=" "+c);a.push({address:e,region:c})}0==a.length?(this.Ct=[],this.rE()):this.er.create(a,gvjs_s(this.XZ,this))};
gvjs_.XZ=function(a){for(var b=[],c=!0,d=a.length,e=0;e<d;e++){var f=this.Z.getValue(e,0);a[e]&&a[e][0]?(c=a[e][0],b.push({name:f,lat:c.geometry.location.lat(),lng:c.geometry.location.lng()}),c=!1):b.push(null)}this.Ct=b;this.rE();c&&0<d&&gvjs_8x(this.Sd,gvjs_oT)};gvjs_.rX=function(){var a=this.m.region;a=gvjs_He(gvjs_dma,a)?"countries_en":a;0==this.Gi?(this.Ct=[],this.rE()):gvjs_RT(a,gvjs_s(function(b){for(var c=[],d=0;d<this.Gi;++d)c.push(this.Z.getValue(d,0));this.Ct=this.WW(c,b);this.rE()},this))};
gvjs_.WW=function(a,b){return gvjs_v(a,function(c){var d=gvjs_kf(gvjs_gg(c)).toLowerCase(),e=b&&gvjs_TT(b,d);return{name:c,lat:null,lng:null,code:e?e:2==d.length||"-"==d.charAt(2)?d.toUpperCase():null}},this)};
gvjs_.rE=function(){var a={};var b=this.Z;var c=Number(this.Nr);if(-1==c)var d=b=0;else{var e=Number(b.getValue(0,c));d=Number(b.getValue(0,c));for(var f=0;f<this.Gi;f++){var g=Number(b.getValue(f,c));e=Math.max(e,g);d=Math.min(d,g)}b=e}a.Minimums=[[d,d]];a.Maximums=[[b,b]];a.TargetId=this.m.region;""==this.m.resolution?gvjs_He(gvjs_dma,a.TargetId)?a.ZoomLevel=gvjs_mT:a.ZoomLevel=this.m.dataMode==gvjs_J_.REGIONS?"PROVINCES":gvjs_mT:a.ZoomLevel=this.m.resolution;a.PrimarySegmentKey=this.m.dataMode==
gvjs_J_.REGIONS?a.ZoomLevel==gvjs_mT?"COUNTRY":"REGION":"CITY";d="Value";-1!=this.Nr&&(d=this.Z.Ga(this.Nr));a.DataLabels=gvjs_jf(gvjs_gg(d))?a.DataLabels=["Value","Value"]:a.DataLabels=[d,d];a.ZoomOutEnabled=this.m.showZoomOut;a.ZoomOutMessage=this.m.zoomOutLabel;a.ParentId="zoomout";a.DataIndex=0;a.Id="google.visualization.GeoMap-"+this.Tra;a.CityColors=this.m.colors;a.RegionColors=this.m.colors;a.LegendEnabled=this.m.showLegend;d=[];for(b=0;b<this.Gi;b++)if(c=0,e="",-1!=this.Nr&&(c=this.Z.getValue(b,
this.Nr),e=this.Z.Ha(b,this.Nr)),f=this.Ct[b])g={},g.Values=[[Number(c),e]],g.ColorKey=Number(c),g.Id=this.m.dataMode==gvjs_J_.MARKERS?b:f.code,g.Lat=f.lat,g.Lng=f.lng,-1!=this.iF?g.Name=this.Z.getValue(b,this.iF):f.name&&(g.Name=f.name),g.Name=g.Name?g.Name.replace(/'/g," "):g.Name,d.push(g);a.Regions=d;this.m.useSvg||(d=gvjs_Hi({GeoMap:a}),gvjs_ema.Ch.filename="geomap.swf",a=gvjs_ef(gvjs_DQ(gvjs_ema)),this.zC||(this.zC=gvjs_dh(gvjs_Ob),this.zC.id="google-visualization-geomap-"+gvjs_fma.toString(),
gvjs_fma+=1,gvjs_hh(this.container),this.container.appendChild(this.zC)),b=this.zC.id.split("-"),b=b[b.length-1],c=parseInt(this.m.width,10),e=parseInt(this.m.height,10),d={staticFilePath:gvjs_ef(gvjs_DQ(gvjs_gma)),locale:"i18n",input:encodeURIComponent(String(d))},new gvjs_EQ.J9(a,this.zC.id,c,e,"9.0.0",!1,d,{menuc:gvjs_Sb,wmode:"opaque",allowScriptAccess:"always",bgcolor:gvjs_xr},{id:"google-visualization-geomap-embed-"+b}));gvjs_I(this,"drawingDone",{});gvjs_I(this,gvjs_i,null)};gvjs_.Jb=function(){this.er.cancel()};
var gvjs_fma=0,gvjs_bma=[];gvjs_=gvjs_I_.prototype;gvjs_.Of=null;gvjs_.m=null;gvjs_.Z=null;gvjs_.Ct=null;gvjs_.XP=null;gvjs_.Nr=-1;gvjs_.iF=-1;gvjs_.Gi=null;
var gvjs_ema=gvjs_FQ("flash","geomap","3"),gvjs_gma=gvjs_FQ("base","geomap","10"),gvjs_J_={REGIONS:0,MARKERS:1},gvjs_dma=["AD","AE","AG","AI","AN","AO","AS","AW","AZ","BB","BF","BH","BI","BJ","BM","BN","BS","BV","BW","CC","CD","CF","CG","CI","CK","CL","CM","CS","CU","CV","CX","DJ","DK","DM","DO","EE","EG","EH","ER","ET","FJ","FK","FM","FO","GA","GD","GE","GF","GG","GH","GI","GL","GM","GP","GQ","GS","GU","GW","HK","HM","HR","HT","IE","IL","IM","IO","IS","JE","JO","KM","KP","KW","KY","KZ","LA","LB",
"LC","LI","LK","LR","LS","LT","LV","LY","MA","MC","MD","MG","MH","MK","ML","MN","MO","MP","MQ","MR","MS","MT","MU","MW","MZ","NA","NC","NE","NF","NG","NO","NR","NU","OM","PF","PH","PM","PN","PR","PW","QA","QM","QN","RE","RO","RU","RW","SB","SC","SD","SE","SG","SH","SI","SJ","SL","SM","SN","SO","ST","SY","SZ","TC",gvjs_us,"TF","TG","TJ","TK","TL","TN","TO","TT","TV","TW","UM","VA","VC","VG","VI","VN","VU","WF","WS","YE","YT","ZM","ZW",gvjs_CT,"005","013","021","002","017","009","053","054","015","018",
"030","034","035","143","145","151","154","155","039","057","061","029","011","014","150"],gvjs_cma=["us_metro"],gvjs_hma=gvjs_Ph();gvjs_hma.onmouseup||(gvjs_hma.onmouseup=function(){});gvjs_q(gvjs_oc,gvjs_I_,void 0);gvjs_I_.prototype.draw=gvjs_I_.prototype.draw;gvjs_I_.prototype.setSelection=gvjs_I_.prototype.setSelection;gvjs_I_.prototype.getSelection=gvjs_I_.prototype.getSelection;
gvjs_q("VisualizationModule.changeGeoMap",function(a,b,c,d){d=d.slice(28);b=gvjs_bma[Number(d)];if("zoomout"==a)gvjs_I(b,"zoomOut",{});else if(gvjs_I(b,"regionClick",{region:a}),b.m.dataMode==gvjs_J_.REGIONS){c=-1;for(d=0;d<b.Gi;d++)if(b.Ct[d]&&b.Ct[d].code==a){c=d;break}-1!=c&&(a=gvjs_do(b.Of,c)?null:[{row:c}],b.setSelection(a),gvjs_I(b,gvjs_k,{}))}},void 0);
