#ifndef KSYNTAXHIGHLIGHTING_VERSION_H
#define KSYNTAXHIGHLIGHTING_VERSION_H

#define KSYNTAXHIGHLIGHTING_VERSION_MAJOR 6
#define KSYNTAXHIGHLIGHTING_VERSION_MINOR 7

#endif // KSYNTAXHIGHLIGHTING_VERSION_H
